carplay_Peralta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('feedback/', include('feedback.urls',namespace='feedback')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('pedidos/', include('pedidos.urls', namespace='pedidos')),
    path('payment/', include('payment.urls',namespace='payment')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

pedidos/urls.py
from django.urls import path
from . import views

app_name = 'pedidos'

urlpatterns = [
    path('create/', views.pedido_create, name='pedido_create'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),

    path('category/<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),

    path('department/<slug:department_slug>/', views.product_list,
         name='product_list_by_department'),

    path('manufacturer/<slug:manufacturer_slug>/', views.product_list,
         name='product_list_by_manufacturer'),
         
    path('<int:id>/<slug:slug>/', views.product_detail,
         name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    cantidad = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,coerce=int)
    override = forms.BooleanField(required=False,
                                  initial=False,
                                widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                quantity=cd['cantidad'],
                override_quantity=cd['override'])
    return redirect('cart:cart_detail')

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity': item['quantity'],
            'override': True})
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
 Your shopping cart
{% endblock %}
{% block content %}
<style>
    .imagen-limitada {
      max-width: 300px;
      max-height: 200px;
      width: auto;
      height: auto;
    }
    .producto {
        display: flex;
        align-items: center;
    }
    .detalles-producto {
        flex-grow: 1;
        
    }

    .btn-search {
        background-color: #f8a976;
        color: #fff;
        border: none;
        padding: 10px 15px;
        border-radius: 4px;
        cursor: pointer;
    }

    .btn-search:hover {
        background-color: #a16e4b;
    }
  </style>

 <h1>Tu carrito de compra</h1>
 {% if cart %}
 <table class="cart">
    <thead>
        <tr>
            <th>Imagen</th>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Eliminar</th>
            <th>Precio unidad</th>
            <th>Precio</th>
        </tr>
    </thead>
    <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="{% if product.image %}{{ product.image.url }}
                            {% else %}{% static "img/no_image.png" %}{% endif %}" class="imagen-limitada">
                        </a>
                    </td>
                        <td>{{ product.name }}</td>
                        <td>
                            <form action="{% url "cart:cart_add" product.id %}" method="post">
                                {{ item.update_quantity_form.cantidad }}
                                {{ item.update_quantity_form.override }}
                            <input type="submit" value="Actualizar">
                            {% csrf_token %}
                            </form>
                        </td>
                        <td>
                        <form action="{% url "cart:cart_remove" product.id %}"method="post">
                            <input type="submit" value="Eliminar">
                            {% csrf_token %}
                        </form>
                        </td>
                    <td class="num">{{ item.price }}€</td>
                    <td class="num">{{ item.total_price }}€</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
        <td>Total</td>
        <td colspan="4"></td>
        <td class="num">{{ cart.get_total_price }}€</td>
        </tr>
    </tbody>
 </table>
 <p class="text-right">
    <a href="{% url "shop:product_list" %}" class="button light">Seguir comprando</a>
    <a href="{% url "pedidos:pedido_create" %}" class="button">
        Terminar pedido
    </a>
 </p>
 {% else %}
    <p>No hay productos en el carrito.</p>
{% endif %}
{% endblock %}