carplay_Peralta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('feedback/', include('feedback.urls',namespace='feedback')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('pedidos/', include('pedidos.urls', namespace='pedidos')),
    path('payment/', include('payment.urls',namespace='payment')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

payment/urls.py
from django.urls import path
from . import views
from . import webhooks

app_name = 'payment'

urlpatterns = [
 path('process/', views.payment_process, name='process'),
 path('completed/', views.payment_completed, name='completed'),
 path('canceled/', views.payment_canceled, name='canceled'),
 path('webhook/', webhooks.stripe_webhook, name='stripe-webhook'),
]

payment/models.py
from django.db import models

# Create your models here.

payment/views.py
from decimal import Decimal
import stripe
from django.conf import settings
from django.core.mail import BadHeaderError, send_mail
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, reverse, get_object_or_404
from pedidos.models import Pedido, PedidoItem
from payment.tasks import payment_completed

# creación de la instancia Stripe 
stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION

def payment_process(request):
    pedido_id = request.session.get('pedido_id',None)
    pedido=get_object_or_404(Pedido, id=pedido_id)

    if request.method == 'POST':
        success_url = request.build_absolute_uri(reverse('payment:completed'))
        cancel_url = request.build_absolute_uri(reverse('payment:canceled'))

        #Stripe checkout session data
        session_data={
            'mode': 'payment',
            'client_reference_id': pedido.id,
            'success_url': success_url,
            'cancel_url': cancel_url,
            'line_items': []
        }
        # add pedido items to the Stripe checkout session
        for item in pedido.items.all():
            session_data['line_items'].append({
                'price_data': {
                    'unit_amount': int(item.price * Decimal('100')),
                    'currency': 'usd',
                    'product_data': {
                        'name': item.product.name,
                    },
                },
                'quantity': item.quantity,
            })
        # create Stripe checkout session
        session = stripe.checkout.Session.create(**session_data)
        #redirect to Stripe payment form
        return redirect(session.url,code=303)
    else:
        return render(request,'payment/process.html',locals())

def payment_completed(request):
    pedido_id = request.session.get('pedido_id',None)
    pedido=get_object_or_404(Pedido, id=pedido_id)
    items=PedidoItem.objects.filter(pedido=pedido).all()
    cadena_items = ""
    for item in items:
        cadena_items = cadena_items + item.__str__() + "\n"
    # Mensaje de confirmación de pago 
    subject = "Recibo de pago" + " " + str(pedido.num_referencia)
    message = pedido.cadena() + "\n" + "He aquí el recibo de su pago por la compra en Carplay Peralta \n" + cadena_items
    from_email = "peraltacarplay@gmail.com"
    to_email = [pedido.email]
    if subject and message and from_email and to_email:
        try:
            send_mail(subject, message, from_email, to_email)
        except BadHeaderError:
            return HttpResponse("Cabecera no encontrada.")
    else:
        # In reality we'd use a form class
        # to get proper validation errors.
        return HttpResponse("Hay campos erróneos en la comprobación de datos")
    return render(request, 'payment/completed.html', {'pedido':pedido})

def payment_canceled(request):
 return render(request, 'payment/cancelled.html')

payment/templates/payment/cancelled.html
{% extends "shop/base.html" %}
{% block title %}Pago cancelado{% endblock %}
{% block content %}
<h1>Tu pago no se ha realizado correctamente</h1>
<p>Tu pago no ha sido satisfactoriamente procesado.</p>
{% endblock %}

payment/templates/payment/completed.html
{% extends "shop/base.html" %}
{% block title %}Pago aceptado{% endblock %}
{% block content %}
 <h1>Tu pago se ha realizado correctamente</h1>
 <p>Tu pago ha sido satisfactoriamente procesado.</p><br>
 <p>Su número de referencia es {{pedido.num_referencia}}, si usted no está registrado procure guardarlo para seguir su pedido</p>
{% endblock %}

payment/templates/payment/process.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}Pasarela de pago{% endblock %}
{% block content %}
 <h1>Resumen de pedido</h1>
 <table class="cart">
 <thead>
    <tr>
        <th>Imagen</th>
        <th>Producto</th>
        <th>Precio</th>
        <th>Cantidad</th>
        <th>Total</th>
    </tr>
</thead>
<tbody>
    {% for item in pedido.items.all %}
    <tr class="row{% cycle "1" "2" %}">
        <td>
            <img src="{% if item.product.image %}{{ item.product.image.url }}
            {% else %}{% static "img/no_image.png" %}{% endif %}">
        </td>
        <td>{{ item.product.name }}</td>
        <td class="num">{{ item.price }}€</td>
        <td class="num">{{ item.quantity }}</td>
        <td class="num">{{ item.get_cost }}€</td>
    </tr>
    {% endfor %}
    <tr class="total">
        <td colspan="4">Total</td>
        <td class="num">{{ pedido.get_total_cost }}€</td>
    </tr>
</tbody>
</table>
<!-- Botón de pasarela de pago -->
<form action="{% url "payment:process" %}" method="post">
    <input type="submit" value="Pagar ahora">
    {% csrf_token %}
</form>
<!-- Botón de pago a contrareembolso -->
<form action="{% url "payment:completed" %}" method="post">
    <input type="submit" value="Pagar contrareembolso">
    {% csrf_token %}
</form>

{% endblock %}